# Pandas DataFrame

Der Datentyp DataFrame ist die wichtigste Datenstruktur in Pandas. Er repräsentiert eine Tabelle ähnlich wie eine ExcelTabelle mit Spalten und Zeilen. Jede Spalte (sowie jede Zeile) ist eine Pandas-Series und damit unter der Haube auch wieder ein Numpy-Array.

Man kann also sagen, dass dieser Datentyp auf Tabellen basiert.

Jede Spalte besteht aus einem eindeutigen Daten-Typen, aber verschiedene Spalten haben verschiedene
Typen, z.B. könnte die erste Spalte vom Typ Integer sein, während die zweite Spalte vom Typ
Boolean und so weiter.

DataFrames lassen sich auf vielfältige Weise erstellen. Wir schauen uns hier mal die wichtigsten an.

## Dataframe aus einem Dictionary erstellen

Ein Dataframe lässt sich besonders einfach aus einem Dictionary erstellen. Die Keys des Dictionaries werden die zukünftigen Spalten, die Werte des Dictionaries werden die Einträge, sofern sie als Sequenz vorliegen. Beim Erstellen eines DataFrames muss darauf geachtet werden, dass die Anzahl der Werte für jeden Key gleich lang sind.

In [ ]:
import pandas as pd

In [2]:
import pandas as pd
names = ["Ron", "Hermione", "Harry"]
points = [3, 2, 4]
d = {"names": names, "points": points}

# Dictionary erstellen und daraus einen Dataframe machen
df = pd.DataFrame(d)
display(df)
print("Data Types: ")
print(df.dtypes)

      names  points
0       Ron       3
1  Hermione       2
2     Harry       4

Data Types:
names     object
points     int64
dtype: object

In [ ]:
df

### Dataframe aus einem zweidimensionalen Numpy Array mit Spaltennamen erstellen

In [4]:
# numpy array
import numpy as np

M = np.random.randint(low=1, high=4, size=(4,2))
spaltennamen = ["size", "value"]

df_2 = pd.DataFrame(M, columns=spaltennamen)
display(df_2)
df_2.shape, df_2.ndim

   size  value
0     3      1
1     1      2
2     3      2
3     1      1

((4, 2), 2)

### Dataframe aus zweidimensionaler Liste erstellen

In [5]:
staff = [
    ["Emma", 29, "HR"],
    ["Oliver", 25, "Finance"],
    ["Harry", 33, "Marketing"],
    ["Sophia", 24, "IT"],
    ["Mandos", 53, "IT"],
]

df_staff = pd.DataFrame(staff, columns=["Name", "Age", "Department"])
print("staff:\n", df_staff)

staff:
      Name  Age Department
0    Emma   29         HR
1  Oliver   25    Finance
2   Harry   33  Marketing
3  Sophia   24         IT
4  Mandos   53         IT

### Dataframe aus einer Liste von Dictionaries erstellen

In [ ]:
staff = [
    {"Name": "Emma", "Age": 29, "Department": "HR"},
    {"Name": "Oliver", "Age": 25, "Department": "Finance"},
    {"Name": "Harry", "Age": 33, "Department": "Finance"},
    {"Name": "Sophia", "Age": 24, "Department": "IT"},
]

df_4 = pd.DataFrame(staff)
df_4

### Spalte im DataFrame adressieren

Eine Spalte in einem Dataframe ist eine Pandas Series. Es gibt zwei Möglichkeiten, eine Spalte zu adressieren:

In [14]:
print("Dot Syntax:\n", df.names)
print()
print("[] Syntax:\n", df["names"])

Dot Syntax:
 0         Ron
1    Hermione
2       Harry
Name: names, dtype: object

[] Syntax:
 0         Ron
1    Hermione
2       Harry
Name: names, dtype: object

### Spalten anzeigen lassen

In [15]:
df.columns, list(df.columns)

(Index(['names', 'points'], dtype='object'), ['names', 'points'])

### Index des Dataframes anzeigen

In [6]:
df.index

RangeIndex(start=0, stop=3, step=1)

### Tail und Head

mit den Funktionen Tail und Head lassen sich die ersten und letzten Einträge eines Dataframes anzeigen. Beide Funktionen erwarten optional die Anzahl der Einträge, die angezeigt werden sollen. Ohne Argument aufgerufen liegt der Defaultwert bei 10

In [19]:
# Zeige die beiden leztten Einträge
df.tail(2)

      names  points
1  Hermione       2
2     Harry       4

In [20]:
# Zeige den ersten Eintrag
df.head(1)

  names  points
0   Ron       3

### Aufgabe

Erstelle ein Dictionary colors, mit folgenden Key-Value Paaren:

red: [3, 4, 2]  
green: [3, 4, "5"]  
blue: [2.2, 4.4, 1.1]

Erstelle aus dem Dictionary einen DataFrame. Zeige den Datentyp jeder Spalte. Ändere den Datentyp für die Spalte `green` in int8. Nutze dazu die Methode `.astype` für ein Series-Objekt.

In [5]:
# a) Erstelle ein Dictionary mit 3 Keys (red, green, blue) und als Wert eine Wert-Liste
# b) Erstelle aus dem Dictionary einen Dataframe
# c) Konvertiere die Spalte green in den Datentyp int8

# Happy Coding!

In [7]:
import pandas as pd

# create dictionary
dictionary = {
    "red": [3, 4, 2],
    "green": [3, 4, "5"],
    "blue": [2.2, 4.4, 1.1]
}

print("a) \n ", dictionary)
print()

# create dataframe
df_aufgabe = pd.DataFrame(dictionary)
print("b) \n ", df_aufgabe)
print()

# convert green-column to int8
df_aufgabe.green = df_aufgabe.green.astype('int8')
# mostrar DatenTyp en cada columna
print("c) \n ", df_aufgabe)
print()
print("extra -> \n", df_aufgabe.dtypes)

a)
  {'red': [3, 4, 2], 'green': [3, 4, '5'], 'blue': [2.2, 4.4, 1.1]}

b)
     red green  blue
0    3     3   2.2
1    4     4   4.4
2    2     5   1.1

c)
     red  green  blue
0    3      3   2.2
1    4      4   4.4
2    2      5   1.1

extra ->
 red        int64
green       int8
blue     float64
dtype: object